`define DEF_SIGNAL_IN_EN
`define DEF_TRIG_0_EN
`define DEF_TRIG_1_EN
`define DEF_TRIG_5_EN
`define DEF_TRIG_6_EN
`define DEF_TRIG_7_EN
`define DEF_TRIG_8_EN
`define DEF_TRIG_9_EN
`define DEF_TRIG_10_EN
`define DEF_TRIG_11_EN
